name: shop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  transformer_page_view: ^0.1.6
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  auto_route: ^4.2.1
  equatable: ^2.0.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  auto_route_generator: ^4.2.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
